(() => {
  const money=n=>Number.isFinite(n)?Math.round(n).toLocaleString('ko-KR')+'원':'-';
  const pct=n=>Number.isFinite(n)?n.toFixed(2)+'%':'-';
  const num=(f,n,d=0)=>{const v=Number((f.querySelector('[name="'+n+'"]')||{}).value);return Number.isFinite(v)?v:d};
  const val=(f,n)=>((f.querySelector('[name="'+n+'"]')||{}).value||'').trim();
  const parseOdds=s=>String(s||'').split(/[,\s]+/).map(Number).filter(n=>Number.isFinite(n)&&n>1);
  const hostOf=u=>{try{return new URL(String(u).includes('://')?u:'https://'+u).hostname.toLowerCase()}catch{return ''}};
  const dist=(a,b)=>{a=a||'';b=b||'';const dp=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)dp[0][j]=j;for(let i=1;i<=a.length;i++){for(let j=1;j<=b.length;j++){dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]===b[j-1]?0:1));}}return dp[a.length][b.length]};
  const render=(id,html)=>{const out=document.querySelector('[data-v52-result="'+id+'"]');if(out)out.innerHTML=html};
  const riskUrl=(url,base)=>{const h=hostOf(url),b=hostOf(base||url)||String(base||'').toLowerCase();const flags=[];if(!String(url||'').toLowerCase().startsWith('https://'))flags.push('HTTPS 아님 또는 스킴 누락');if(h.includes('xn--'))flags.push('punycode 도메인');if(h&&b&&h!==b&&!h.endsWith('.'+b))flags.push('기준 도메인과 불일치');if((h.match(/-/g)||[]).length>=2)flags.push('하이픈 과다');if(/0|1|3|5|7/.test(h.replace(b,'')))flags.push('숫자 치환 가능성');if(h.split('.').length>b.split('.').length+1)flags.push('서브도메인 단계 과다');return{h,b,flags,d:dist(h.replace(/[^a-z0-9]/g,''),b.replace(/[^a-z0-9]/g,''))}};
  const calcs={
    'official-url':f=>{const r=riskUrl(val(f,'url'),val(f,'base'));render('official-url','<strong>도메인:</strong> '+(r.h||'-')+'<br><strong>기준:</strong> '+(r.b||'-')+'<br><strong>문자열 거리:</strong> '+r.d+'<br><strong>확인 신호:</strong> '+(r.flags.length?r.flags.join(' · '):'큰 변조 신호 없음'))},
    'join-code':f=>{const [provider,code]=(val(f,'provider')||'|').split('|');const input=val(f,'code');const ok=input.toLowerCase()===String(code).toLowerCase();render('join-code','<strong>'+provider+'</strong><br>기준 코드: <b>'+code+'</b><br>입력 코드: <b>'+input+'</b><br>결과: '+(ok?'일치':'불일치 또는 대소문자/공백 확인 필요'))},
    'bonus-net':f=>{const dep=num(f,'deposit'),br=num(f,'bonusRate')/100,roll=num(f,'rolling'),c=Math.max(num(f,'contribution')/100,.01);const bonus=dep*br,total=dep+bonus,turnover=total*roll/c;render('bonus-net','보너스: <b>'+money(bonus)+'</b><br>총 크레딧: <b>'+money(total)+'</b><br>필요 롤링: <b>'+money(turnover)+'</b>')},
    'rolling':f=>{const base=num(f,'base'),m=num(f,'multiple'),p=num(f,'progress'),c=Math.max(num(f,'contribution')/100,.01);const need=base*m/c,done=p*c,remain=Math.max(need-done,0);render('rolling','필요 롤링: <b>'+money(need)+'</b><br>인정 진행액: <b>'+money(done)+'</b><br>남은 롤링: <b>'+money(remain)+'</b>')},
    'withdraw':f=>{const bal=num(f,'balance'),cap=num(f,'cap'),rem=num(f,'remaining');const possible=rem>0?0:Math.min(bal,cap||bal);render('withdraw','현재 잔액: <b>'+money(bal)+'</b><br>최대 한도 반영: <b>'+money(cap||bal)+'</b><br>남은 롤링: <b>'+money(rem)+'</b><br>즉시 출금 가능 추정: <b>'+money(possible)+'</b>')},
    'first-recurring':f=>{const dep=num(f,'deposit'),fr=num(f,'firstRate')/100,rr=num(f,'recRate')/100,froll=num(f,'firstRolling'),rroll=num(f,'recRolling');const fb=dep*fr,rb=dep*rr;render('first-recurring','첫충 보너스: <b>'+money(fb)+'</b> / 필요 롤링: <b>'+money((dep+fb)*froll)+'</b><br>매충 보너스: <b>'+money(rb)+'</b> / 필요 롤링: <b>'+money((dep+rb)*rroll)+'</b>')},
    'overround':f=>{const odds=parseOdds(val(f,'odds'));const sum=odds.reduce((a,o)=>a+1/o,0);render('overround','입력 배당: '+odds.join(' / ')+'<br>내재확률 합계: <b>'+pct(sum*100)+'</b><br>오버라운드: <b>'+pct((sum-1)*100)+'</b><br>환수율 추정: <b>'+pct(100/sum)+'</b>')},
    'ev':f=>{const o=num(f,'odds'),p=num(f,'prob')/100;render('ev','손익분기 확률: <b>'+pct(100/o)+'</b><br>공정 배당: <b>'+(p>0?(1/p).toFixed(3):'-')+'</b><br>EV: <b>'+pct((o*p-1)*100)+'</b>')},
    'combo':f=>{const odds=parseOdds(val(f,'odds')),stake=num(f,'stake');const total=odds.reduce((a,o)=>a*o,1),payout=stake*total;render('combo','총 조합 배당: <b>'+total.toFixed(3)+'</b><br>예상 지급액: <b>'+money(payout)+'</b><br>순손익: <b>'+money(payout-stake)+'</b>')},
    'slot-rtp':f=>{const stake=num(f,'stake'),spins=num(f,'spins'),rtp=num(f,'rtp')/100;const total=stake*spins,ret=total*rtp;render('slot-rtp','총 투입액: <b>'+money(total)+'</b><br>이론 환급: <b>'+money(ret)+'</b><br>이론 손실: <b>'+money(total-ret)+'</b>')},
    'martingale':f=>{const base=num(f,'base'),mul=num(f,'multiplier'),bank=num(f,'bankroll'),p=num(f,'winProb')/100,q=1-p;let need=0,step=0,bet=base;while(need+bet<=bank&&step<50){need+=bet;bet*=mul;step++;}render('martingale','감당 가능 연속 단계: <b>'+step+'단계</b><br>누적 필요 자본: <b>'+money(need)+'</b><br>다음 배팅액: <b>'+money(bet)+'</b><br>단순 연패 위험: <b>'+pct(Math.pow(q,Math.max(step,1))*100)+'</b>')},
    'phishing':f=>{const r=riskUrl(val(f,'url'),val(f,'base'));render('phishing','검사 도메인: <b>'+(r.h||'-')+'</b><br>기준 도메인: <b>'+(r.b||'-')+'</b><br>문자열 거리: <b>'+r.d+'</b><br>변조 신호: <b>'+(r.flags.length?r.flags.join(' · '):'큰 변조 신호 없음')+'</b>')}
  };
  document.addEventListener('click',e=>{const open=e.target.closest('[data-v52-open]');if(open){const id=open.dataset.v52Open;document.querySelectorAll('[data-v52-open]').forEach(x=>x.classList.toggle('is-active',x===open));document.querySelectorAll('[data-v52-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.v52Panel===id));history.replaceState(null,'','#tool-'+id)}const calc=e.target.closest('[data-v52-calc]');if(calc){const id=calc.dataset.v52Calc;const form=calc.closest('[data-v52-form]');if(calcs[id])calcs[id](form)}});
  document.addEventListener('input',e=>{if(e.target&&e.target.id==='v52ToolSearch'){const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.v52-tool-card').forEach(card=>{card.hidden=q&&!card.textContent.toLowerCase().includes(q)})}});
  document.querySelectorAll('[data-v52-calc]').forEach(btn=>btn.click());
})();
